"""``pptspine._core`` —— Rust 扩展模块的类型存根(PEP 561)。

形状 / OCR 结果以 ``dict[str, Any]`` 返回(可自省);键见 README。
"""

from __future__ import annotations

from os import PathLike
from typing import Any

__version__: str

class PptError(Exception):
    """pptspine 异常层级的根。"""

class PptZipError(PptError): ...
class PptXmlError(PptError): ...
class PptUnsupportedError(PptError): ...
class PptOcrError(PptError): ...

class Slide:
    """一张幻灯片句柄。"""

    @property
    def index(self) -> int: ...
    @property
    def layout_name(self) -> str | None: ...
    @property
    def master_name(self) -> str | None: ...
    def shapes(self) -> list[dict[str, Any]]: ...

class Presentation:
    """一份已解析的演示文稿句柄。"""

    @property
    def slide_count(self) -> int: ...
    @property
    def slide_size(self) -> tuple[int, int]: ...
    @property
    def slide_size_points(self) -> tuple[float, float]: ...
    def slides(self) -> list[Slide]: ...
    def slide(self, index: int) -> Slide: ...
    def __len__(self) -> int: ...

def version() -> str: ...
def open(path: str | PathLike[str]) -> Presentation: ...
def open_bytes(data: bytes) -> Presentation: ...
def ocr_image(data: bytes) -> list[dict[str, Any]]: ...
